[features]
seeds = false
skip-lint = false
[programs.localnet]
swipe = "DntPpuc8ea7jLLB6CbHSwzEaAtkHKGTuNwiW57tNRXN6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/alicehume/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
